import { MenuItemIngredient } from './../models/menuItemIngredient.model';

export const menuItemIngredientList: MenuItemIngredient[] = [
  new MenuItemIngredient(1, 'Ground Beef, 10#', 1, 1),
  new MenuItemIngredient(2, 'Hot Dogs, 3-Dozen', 1, 1),
  new MenuItemIngredient(3, 'Baked Beans, #10 Can', 1, 1),
  new MenuItemIngredient(4, 'Potato Chips, 2 Large Bags', 1, 1),
  new MenuItemIngredient(5, 'Cole Slaw, 1 Tub', 1, 1),
  new MenuItemIngredient(6, 'Hamburger Buns, 3-Dozen', 1, 1),
  new MenuItemIngredient(7, 'Hot Dog Buns, 3-Dozen', 1, 1),
  new MenuItemIngredient(8, 'Tea Bags, Lipton, 1 Box', 1, 1),
  new MenuItemIngredient(9, 'Ketchup, Mayonnaise, Mustard, Relish', 1, 1),
  new MenuItemIngredient(10, 'Bacon, 4#', 1, 1),
  new MenuItemIngredient(11, 'Eggs, 2-Dozen', 1, 1),
  new MenuItemIngredient(12, 'Heavy Cream, 1-Quart', 1, 1),
  new MenuItemIngredient(13, 'Pie Shells, 4', 1, 1),
  new MenuItemIngredient(14, 'Potatoes, 5# Bag', 1, 1),
  new MenuItemIngredient(15, 'Butter, 1#', 1, 1),
  new MenuItemIngredient(16, 'Fruit Assortment, 2 Tubs', 1, 1),
  new MenuItemIngredient(17, 'Cinnamon Rolls, 4 Cans', 1, 1),
  new MenuItemIngredient(18, 'Bloody Mary Mix, 2 Bottles', 1, 1),
  new MenuItemIngredient(19, 'Vodka, 2-Litres', 1, 1),
  new MenuItemIngredient(20, 'Beef Brisket, 5#', 1, 1),
  new MenuItemIngredient(21, 'Corned Beef Spices', 1, 1),
  new MenuItemIngredient(22, 'Red Potatoes, 5#', 1, 1),
  new MenuItemIngredient(23, '1/2 and 1/2, 2-Quarts', 1, 1),
  new MenuItemIngredient(24, 'Brussels Sprouts, Frozen, 2#', 1, 1),
  new MenuItemIngredient(25, 'Soda Bread, 2-Dozen Pieces', 1, 1),
  new MenuItemIngredient(25, 'Irish Whiskey, 2-Litres', 1, 1)
];
