import { MenuItemIngredient } from './../models/menuItemIngredient';

menuItemIngredients: MenuItemIngredient[] = [
  new MenuItemIngredient(1, 'Ground Beef, 10#');
  new MenuItemIngredient(2, 'Hot Dogs, 3-Dozen');
  new MenuItemIngredient(3, 'Baked Beans, #10 Can');
  new MenuItemIngredient(4, 'Potato Chips, 2 Large Bags');
  new MenuItemIngredient(5, 'Cole Slaw, 1 Tub');
  new MenuItemIngredient(6, 'Hamburger Buns, 3-Dozen');
  new MenuItemIngredient(7, 'Hot Dog Buns, 3-Dozen');
  new MenuItemIngredient(8, 'Tea Bags, Lipton, 1 Box');
  new MenuItemIngredient(9, 'Ketchup, Mayonnaise, Mustard, Relish');
  new MenuItemIngredient(10, 'Bacon, 4#');
  new MenuItemIngredient(11, 'Eggs, 2-Dozen');
  new MenuItemIngredient(12, 'Heavy Cream, 1-Quart');
  new MenuItemIngredient(13, 'Pie Shells, 4');
  new MenuItemIngredient(14, 'Potatoes, 5# Bag');
  new MenuItemIngredient(15, 'Butter, 1#');
  new MenuItemIngredient(16, 'Fruit Assortment, 2 Tubs');
  new MenuItemIngredient(17, 'Cinnamon Rolls, 4 Cans');
  new MenuItemIngredient(18, 'Bloody Mary Mix, 2 Bottles');
  new MenuItemIngredient(19, 'Vodka, 2-Litres');
  new MenuItemIngredient(20, 'Beef Brisket, 5#');
  new MenuItemIngredient(21, 'Corned Beef Spices');
  new MenuItemIngredient(22, 'Red Potatoes, 5#');
  new MenuItemIngredient(23, '1/2 and 1/2, 2-Quarts');
  new MenuItemIngredient(24, 'Brussels Sprouts, Frozen, 2#');
  new MenuItemIngredient(25, 'Soda Bread, 2-Dozen Pieces');
  new MenuItemIngredient(25, 'Irish Whiskey, 2-Litres');
];
